CREATE TABLE INASISTENCIAS(
    ID_CLUB_GRUPO NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_CLUB_GRUPO NOT NULL,
    ID_CLUB_MEMB NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_CLUB_MEMBRESIA NOT NULL,
    ID_GRUPO_ASIG NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_GRUPO_ASIGNACION NOT NULL,
    ID_LECTOR NUMBER(3) CONSTRAINT NN_INASISTENCIA_ID_LECTOR NOT NULL,
    F_ING_CLUB DATE CONSTRAINT NN_INASISTENCIA_F_ING_CLUB NOT NULL,
    F_ING_GRUPO DATE CONSTRAINT NN_INASISTENCIA_F_ING_GRUPO NOT NULL,
    ID_CLUB_CAL NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_CLUB_CALENDARIO NOT NULL,
    ID_GRUPO_CAL NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_GRUPO_CALENDARIO NOT NULL,
    ISBN NUMBER(13) CONSTRAINT NN_INASISTENCIA_ISBN_LIBRO NOT NULL,
    F_REUNION DATE CONSTRAINT NN_INASISTENCIA_F_REUNION NOT NULL,
    CONSTRAINT FK_INASISTENCIA_ASIGNACION FOREIGN KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT FK_INASISTENCIA_CALENDARIO FOREIGN KEY(ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
        REFERENCES CAL_REUNIONES(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT PK_INASISTENCIA PRIMARY KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO, ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
);
