CREATE TABLE HIST_MEMBRESIAS(
    ID_CLUB NUMBER(2) CONSTRAINT NN_MEMBRESIA_ID_CLUB NOT NULL,
    ID_LECTOR NUMBER(3) CONSTRAINT NN_MEMBRESIA_ID_LECTOR NOT NULL,
    F_ING_CLUB DATE DEFAULT SYSDATE CONSTRAINT NN_MEMBRESIA_F_ING_CLUB NOT NULL,
    F_SOL_RETIRO DATE,
    F_RETIRO DATE,
    MOTIVO_RETIRO VARCHAR2(2) CONSTRAINT CHECK_MEMBRESIA_MOTIVO_RETIRO CHECK(MOTIVO_RETIRO IN ('DE', 'VO', 'IN', 'OT')),
    CONSTRAINT FK_MEMBRESIA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT FK_MEMBRESIA_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT PK_HIST_MEMBRESIA PRIMARY KEY(ID_CLUB, ID_LECTOR, F_ING_CLUB)
);

CREATE TABLE OBRAS_ACTUADAS(
    ID_CLUB NUMBER(2) CONSTRAINT NN_OBRA_ID_CLUB NOT NULL,
    ID_OBRA NUMBER(2) CONSTRAINT NN_OBRA_ID_OBRA NOT NULL,
    TITULO VARCHAR2(50) CONSTRAINT NN_OBRA_TITULO NOT NULL,
    DURACION_MINUTOS NUMBER(3) CONSTRAINT NN_OBRA_DURACION NOT NULL,
    DESCRIPCION VARCHAR2(200) CONSTRAINT NN_OBRA_DESCRIPCION NOT NULL,
    ACTIVA VARCHAR2(1) CONSTRAINT NN_OBRA_ACTIVA NOT NULL CONSTRAINT CHECK_OBRA_ACTIVA CHECK(ACTIVA = 'S' OR ACTIVA = 'N'),
    COSTO NUMBER(6, 2),
    CONSTRAINT FK_OBRA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_OBRA PRIMARY KEY(ID_CLUB, ID_OBRA)
);

CREATE TABLE ASOCIACIONES(
    ID_CLUB NUMBER(2) CONSTRAINT NN_ASOCIACION_ID_CLUB NOT NULL,
    ID_SOCIO NUMBER(2) CONSTRAINT NN_ASOCIACION_ID_SOCIO NOT NULL,
    DESCRIPCION VARCHAR2(200) CONSTRAINT NN_ASOCIACION_DESCRIPCION NOT NULL,
    CONSTRAINT FK_ASOCIACION_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT FK_ASOCIACION_SOCIO FOREIGN KEY(ID_SOCIO) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_ASOCIACION PRIMARY KEY(ID_CLUB, ID_SOCIO)
);

CREATE TABLE TELEFONOS(
    CODIGO_PAIS NUMBER(3) CONSTRAINT NN_TELEFONO_CODIGO_PAIS NOT NULL,
    CODIGO_AREA NUMBER(5) CONSTRAINT NN_TELEFONO_CODIGO_AREA NOT NULL,
    NUMERO NUMBER(9) CONSTRAINT NN_TELEFONO_NUMERO NOT NULL,
    ID_LECTOR NUMBER(3),
    ID_CLUB NUMBER(2),
    CONSTRAINT PK_TELEFONO PRIMARY KEY (CODIGO_PAIS, CODIGO_AREA, NUMERO),
    CONSTRAINT FK_TELEFONO_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT FK_TELEFONO_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT CHECK_ARCO_TELEFONO CHECK(
        (ID_LECTOR IS NULL AND ID_CLUB IS NOT NULL) OR
        (ID_LECTOR IS NOT NULL AND ID_CLUB IS NULL)
    )
);

CREATE TABLE HABLA(
    ID_IDIOMA NUMBER(2) CONSTRAINT NN_HABLA_ID_IDIOMA NOT NULL,
    ID_HABLA NUMBER(2) CONSTRAINT NN_HABLA_ID_HABLA NOT NULL,
    ID_LECTOR NUMBER(3),
    ID_CLUB NUMBER(2),
    CONSTRAINT FK_HABLA_IDIOMA FOREIGN KEY(ID_IDIOMA) REFERENCES IDIOMAS(ID_IDIOMA),
    CONSTRAINT FK_HABLA_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT FK_HABLA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_HABLA PRIMARY KEY(ID_IDIOMA, ID_HABLA),
    CONSTRAINT CHECK_ARCO_HABLA CHECK(
        (ID_LECTOR IS NULL AND ID_CLUB IS NOT NULL) OR
        (ID_LECTOR IS NOT NULL AND ID_CLUB IS NULL)
    )
);

CREATE TABLE GRUPOS_LECTURA(
    ID_CLUB NUMBER(2) CONSTRAINT NN_GRUPO_ID_CLUB NOT NULL,
    ID_GRUPO NUMBER(2) CONSTRAINT NN_GRUPO_ID_GRUPO NOT NULL,
    TIPO VARCHAR2(1) CONSTRAINT NN_GRUPO_TIPO NOT NULL CONSTRAINT CHECK_GRUPO_TIPO CHECK(TIPO IN('N', 'J', 'A')),
    DIA NUMBER(1) CONSTRAINT NN_GRUPO_DIA NOT NULL CONSTRAINT CHECK_GRUPO_DIA CHECK(DIA >= 2 AND DIA <= 6),
    HORA DATE CONSTRAINT NN_GRUPO_HORA NOT NULL CONSTRAINT CHECK_GRUPO_HORA CHECK(TO_CHAR(HORA, 'HH24:MI') BETWEEN '17:00' AND '19:00'),
    F_CREACION DATE DEFAULT SYSDATE CONSTRAINT NN_GRUPO_F_CREACION NOT NULL,
    CONSTRAINT FK_GRUPO_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_GRUPO PRIMARY KEY(ID_CLUB, ID_GRUPO),
    CONSTRAINT CHECK_HORA_NINOS CHECK (TIPO <> 'N' OR TO_CHAR(HORA, 'HH24:MI') = '17:00')
);