CREATE TABLE PAGOS_MEMBRESIA (
    id_club NUMBER(2) CONSTRAINT NN_PAGO_ID_CLUB NOT NULL,
    id_lector NUMBER(3) CONSTRAINT NN_PAGO_ID_LECTOR NOT NULL,
    f_ing_club DATE CONSTRAINT NN_PAGO_F_ING_CLUB NOT NULL,
    id_pago NUMBER(2) CONSTRAINT NN_PAGO_ID_PAGO NOT NULL,
    f_pago DATE DEFAULT SYSDATE CONSTRAINT NN_PAGO_F_PAGO NOT NULL,
    CONSTRAINT FK_PAGOS_MEMB_HIST FOREIGN KEY (id_club, id_lector, f_ing_club) 
        REFERENCES HIST_MEMBRESIAS(id_club, id_lector, f_ing_club),
    CONSTRAINT PK_PAGOS_MEMBRESIA PRIMARY KEY (id_club, id_lector, f_ing_club, id_pago)
);

CREATE TABLE HIST_ASIGNACIONES (
    id_club_grupo NUMBER(2) CONSTRAINT NN_ASIGNACION_ID_CLUB NOT NULL,
    id_grupo NUMBER(2) CONSTRAINT NN_ASIGNACION_ID_GRUPO NOT NULL,
    id_club_memb NUMBER(2) CONSTRAINT NN_ASIGNACION_ID_CLUB_MEMB NOT NULL,
    id_lector NUMBER(3) CONSTRAINT NN_ASIGNACION_ID_LECTOR NOT NULL,
    f_ing_club DATE CONSTRAINT NN_ASIGNACION_F_ING_CLUB NOT NULL,
    f_ing_grupo DATE DEFAULT SYSDATE CONSTRAINT NN_ASIGNACION_F_ING_GRUPO NOT NULL,
    f_fin_grupo DATE,
    CONSTRAINT FK_ASIGNACION_GRUPO FOREIGN KEY(ID_CLUB_GRUPO, ID_GRUPO) 
        REFERENCES GRUPOS_LECTURA(ID_CLUB, ID_GRUPO),
    CONSTRAINT FK_ASIGNACION_MEMBRESIA FOREIGN KEY(ID_CLUB_MEMB, ID_LECTOR, F_ING_CLUB) 
        REFERENCES HIST_MEMBRESIAS(ID_CLUB, ID_LECTOR, F_ING_CLUB),
    CONSTRAINT PK_ASIGNACION  PRIMARY KEY(ID_CLUB_GRUPO, ID_GRUPO, ID_CLUB_MEMB, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
);

CREATE TABLE ADAPTACIONES (
    id_club NUMBER(2) CONSTRAINT NN_ADAPTACION_ID_CLUB NOT NULL,
    id_obra NUMBER(2) CONSTRAINT NN_ADAPTACION_ID_OBRA NOT NULL,
    isbn NUMBER(13) CONSTRAINT NN_ADAPTACION_ISBN NOT NULL,
    CONSTRAINT FK_ADAP_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT FK_ADAP_LIBRO FOREIGN KEY (isbn) REFERENCES LIBROS(isbn),
    CONSTRAINT PK_ADAPTACIONES PRIMARY KEY (id_club, id_obra, isbn)
);

CREATE TABLE ELENCOS (
    id_club NUMBER(2) CONSTRAINT NN_ELENCO_ID_CLUB NOT NULL,
    id_obra NUMBER(2) CONSTRAINT NN_ELENCO_ID_OBRA NOT NULL,
    id_lector NUMBER(3) CONSTRAINT NN_ELENCO_ID_LECTOR NOT NULL,
    CONSTRAINT FK_ELEN_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT FK_ELEN_LECTOR FOREIGN KEY (id_lector) REFERENCES LECTORES(id_lector),
    CONSTRAINT PK_ELENCOS PRIMARY KEY (id_club, id_obra, id_lector)
);

CREATE TABLE PRESENTACIONES (
    id_club NUMBER(2) CONSTRAINT NN_PRESENTACION_ID_CLUB NOT NULL,
    id_obra NUMBER(2) CONSTRAINT NN_PRESENTACION_ID_OBRA NOT NULL,
    f_presentacion DATE CONSTRAINT NN_PRESENTACION_FECHA NOT NULL,
    valoracion NUMBER(3,2) CONSTRAINT NN_PRESENTACION_VALORACION NOT NULL 
        CONSTRAINT CHECK_PRESENTACION_VALORACION CHECK((VALORACION >= 0) AND (VALORACION <= 5)),
    n_entradas NUMBER(2) CONSTRAINT NN_PRESENTACION_ENTRADAS NOT NULL,
    CONSTRAINT FK_PRES_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT PK_PRESENTACIONES PRIMARY KEY (id_club, id_obra, f_presentacion)
);