CREATE TABLE MEJORES_ACTORES (
    id_club_el NUMBER(2) CONSTRAINT NN_MEJOR_ACTOR_ID_CLUB_ELENCO NOT NULL,
    id_obra_el NUMBER(2) CONSTRAINT NN_MEJOR_ACTOR_ID_OBRA_ELENCO NOT NULL,
    id_lector NUMBER(3) CONSTRAINT NN_MEJOR_ACTOR_ID_LECTOR NOT NULL,
    id_club_pres NUMBER(2) CONSTRAINT NN_MEJOR_ACTOR_ID_CLUB_PRESENTACION NOT NULL,
    id_obra_pres NUMBER(2) CONSTRAINT NN_MEJOR_ACTOR_ID_OBRA_PRESENTACION NOT NULL,
    f_presentacion DATE CONSTRAINT NN_MEJOR_ACTOR_F_PRESENTACION NOT NULL,
    CONSTRAINT FK_MEJOR_ACTOR_ELENCO FOREIGN KEY(ID_CLUB_EL, ID_OBRA_EL, ID_LECTOR)
        REFERENCES ELENCOS(ID_CLUB, ID_OBRA, ID_LECTOR),
    CONSTRAINT FK_MEJOR_ACTOR_PRESENTACION FOREIGN KEY(ID_CLUB_PRES, ID_OBRA_PRES, F_PRESENTACION)
        REFERENCES PRESENTACIONES(ID_CLUB, ID_OBRA, F_PRESENTACION),
    CONSTRAINT PK_MEJOR_ACTOR PRIMARY KEY(ID_CLUB_EL, ID_OBRA_EL, ID_LECTOR, ID_CLUB_PRES, ID_OBRA_PRES, F_PRESENTACION)
);

CREATE TABLE CAL_REUNIONES (
    id_club NUMBER(2) CONSTRAINT NN_CALENDARIO_ID_CLUB NOT NULL,
    id_grupo NUMBER(2) CONSTRAINT NN_CALENDARIO_ID_GRUPO NOT NULL,
    isbn NUMBER(13) CONSTRAINT NN_CALENDARIO_ISBN NOT NULL,
    f_reunion DATE CONSTRAINT NN_CALENDARIO_F_REUNION NOT NULL,
    realizada VARCHAR2(1) CONSTRAINT NN_CALENDARIO_REALIZADA NOT NULL CONSTRAINT CHECK_REUNION_REALIZADA CHECK(realizada = 'S' OR realizada = 'N'),
    id_club_memb_mod NUMBER(2) CONSTRAINT NN_CALENDARIO_ID_CLUB_MEMBRESIA_MOD NOT NULL,
    id_club_grupo_mod NUMBER(2) CONSTRAINT NN_CALENDARIO_ID_CLUB_GRUPO_MOD NOT NULL,
    id_grupo_mod NUMBER(2) CONSTRAINT NN_CALENDARIO_ID_GRUPO_MOD NOT NULL,
    id_moderador NUMBER(3) CONSTRAINT NN_ID_MODERADOR NOT NULL,
    f_ing_club_mod DATE CONSTRAINT NN_F_ING_CLUB_MOD NOT NULL,
    f_ing_grupo_mod DATE CONSTRAINT NN_F_ING_GRUPO_MOD NOT NULL,
    conclusiones VARCHAR2(400),
    valoracion NUMBER(1) CONSTRAINT CHECK_REUNION_VALORACION CHECK(valoracion >= 1 AND valoracion <= 5),
    ultima_reunion VARCHAR2(1) CONSTRAINT CHECK_ULTIMA__REUNION CHECK(ultima_reunion = 'S' OR ultima_reunion = 'N'),
    CONSTRAINT FK_GRUPO_CALENDARIO FOREIGN KEY(ID_CLUB, ID_GRUPO) REFERENCES GRUPOS_LECTURA(ID_CLUB, ID_GRUPO),
    CONSTRAINT FK_LIBRO_CALENDARIO FOREIGN KEY(ISBN) REFERENCES LIBROS(ISBN),
    CONSTRAINT FK_MODERADOR FOREIGN KEY(ID_CLUB_MEMB_MOD, ID_CLUB_GRUPO_MOD, ID_GRUPO_MOD, ID_MODERADOR, F_ING_CLUB_MOD, F_ING_GRUPO_MOD)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB_MEMB, ID_CLUB_GRUPO, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT PK_CALENDARIO PRIMARY KEY(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT CHECK_REUNION_OPCIONALES CHECK(realizada = 'N' or NVL(ultima_reunion, 'N') = 'N' or (conclusiones IS NOT NULL AND valoracion is NOT NULL))
);
