CREATE TABLE INASISTENCIAS(
    ID_CLUB NUMBER(3) CONSTRAINT NN_ASISTENCIA_ID_CLUB NOT NULL,
    ID_GRUPO NUMBER(2) CONSTRAINT NN_ASISTENCIA_ID_GRUPO NOT NULL,
    ID_LECTOR NUMBER(5) CONSTRAINT NN_ASISTENCIA_ID_LECTOR NOT NULL,
    F_ING_CLUB DATE CONSTRAINT NN_ASISTENCIA_F_ING_CLUB NOT NULL,
    F_ING_GRUPO DATE CONSTRAINT NN_ASISTENCIA_F_ING_GRUPO NOT NULL,
    ISBN NUMBER(13) CONSTRAINT NN_ASISTENCIA_ISBN NOT NULL,
    F_REUNION DATE CONSTRAINT NN_ASISTENCIA_F_REUNION NOT NULL,
    CONSTRAINT FK_INASISTENCIA_ASIGNACION FOREIGN KEY(ID_CLUB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT FK_INASISTENCIA_CALENDARIO FOREIGN KEY(ID_CLUB, ID_GRUPO, ISBN, F_REUNION)
        REFERENCES CAL_REUNIONES(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT PK_INASISTENCIA PRIMARY KEY(ID_CLUB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO, ISBN, F_REUNION),
    CONSTRAINT CHECK_ING_GRUPO_ANTES_REUNION CHECK(F_ING_GRUPO <= F_REUNION)
);