CREATE TABLE autores (
    id_autor NUMBER(2) CONSTRAINT pk_autor PRIMARY KEY,
    nombre VARCHAR2(20),
    apellido VARCHAR2(20),
    seudonimo VARCHAR2(40),
    CONSTRAINT check_autores_opcionales CHECK(nombre IS NOT NULL or apellido IS NOT NULL or seudonimo IS NOT NULL)
);

CREATE TABLE representantes (
    id_representante NUMBER(2) CONSTRAINT pk_representante PRIMARY KEY,
    primer_nombre VARCHAR2(20) NOT NULL,
    primer_apellido VARCHAR2(20) NOT NULL,
    segundo_apellido VARCHAR2(20) NOT NULL,
    doc_identidad NUMBER(9) NOT NULL,
    segundo_nombre VARCHAR2(20)
);

CREATE TABLE instituciones (
    id_institucion NUMBER(2) CONSTRAINT pk_institucion PRIMARY KEY,
    nombre VARCHAR2(60) NOT NULL,
    tipo VARCHAR2(2) NOT NULL CONSTRAINT check_tipo_institucion CHECK(tipo IN('BI','UN','CO','OT')),  
    descripcion VARCHAR2(200) NOT NULL
);

CREATE TABLE idiomas (
    id_idioma NUMBER(2) CONSTRAINT pk_idioma PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL
);

CREATE TABLE paises (
    id_pais NUMBER(2) CONSTRAINT pk_pais PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    moneda VARCHAR2(3) NOT NULL,
    nacionalidad VARCHAR2(20) NOT NULL
);

CREATE TABLE lectores(
    id_lector NUMBER(3) CONSTRAINT pk_lector PRIMARY KEY,
    primer_nombre VARCHAR2(20) NOT NULL,
    primer_apellido VARCHAR2(20) NOT NULL,
    segundo_apellido VARCHAR2(20) NOT NULL,
    f_nacimiento DATE NOT NULL,
    email VARCHAR2(50) NOT NULL CONSTRAINT u_email_lector UNIQUE,
    doc_identidad NUMBER(9) NOT NULL,
    id_paislector NUMBER(2) NOT NULL ,
    segundo_nombre VARCHAR2(20),
    id_rep_ext NUMBER(2),
    id_rep_int NUMBER(3),
    CONSTRAINT fk_pais_lector FOREIGN KEY (id_paislector) REFERENCES paises(id_pais),
    CONSTRAINT fk_id_repexterno FOREIGN KEY (id_rep_ext) REFERENCES representantes(id_representante),
    CONSTRAINT fk_id_repinter FOREIGN KEY (id_rep_int) REFERENCES lectores (id_lector),
    CONSTRAINT ck_arcorepresentantelector CHECK (id_rep_ext IS NULL or id_rep_int IS NULL)
);

CREATE TABLE libros (
    ISBN NUMBER(13) CONSTRAINT pk_libro PRIMARY KEY,
    titulo VARCHAR2(60) NOT NULL,
    ano_publicacion DATE NOT NULL,
    n_paginas NUMBER (4) NOT NULL,
    sinopsis VARCHAR2(300) NOT NULL,
    tema VARCHAR2(100) NOT NULL,
    tipo_narrativa VARCHAR2(2) NOT NULL CONSTRAINT ck_tiponarrativa CHECK (tipo_narrativa in ('NO','CU','MI','LE','FA','EP')),
    id_paislibro NUMBER(2) NOT NULL,
    id_anterior NUMBER(13) CONSTRAINT u_libro UNIQUE,
    CONSTRAINT fk_paislibro FOREIGN KEY (id_paislibro) REFERENCES paises (id_pais),
    CONSTRAINT fk_anteriorlibro FOREIGN KEY (id_anterior) REFERENCES libros (ISBN)
);

CREATE TABLE ciudades (
    id_pais NUMBER(2) NOT NULL,
    id_ciudad NUMBER(2) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_paisciudad FOREIGN KEY (id_pais) REFERENCES paises (id_pais),
    CONSTRAINT pk_ciudades PRIMARY KEY(id_pais, id_ciudad)
);

CREATE TABLE preferencias(
    id_lector NUMBER(3) NOT NULL,
    ISBN NUMBER(13) NOT NULL,
    orden number(1) NOT NULL CONSTRAINT ck_ordenpref CHECK (orden in(1,2,3)),
    CONSTRAINT fk_lectorpref FOREIGN KEY (id_lector) REFERENCES lectores(id_lector),
    CONSTRAINT fk_isbnlibro FOREIGN KEY (ISBN) REFERENCES libros(ISBN),
    CONSTRAINT pk_preferencias PRIMARY KEY (id_lector, ISBN, orden)
);

CREATE TABLE autorias(
    id_autor NUMBER(2) NOT NULL,
    ISBN NUMBER(13) NOT NULL,
    CONSTRAINT fk_idautoautoria FOREIGN KEY (id_autor) REFERENCES autores(id_autor),
    CONSTRAINT fk_isbnautoria FOREIGN KEY (ISBN) REFERENCES libros(ISBN),
    CONSTRAINT pk_autoria PRIMARY KEY (id_autor, ISBN)
);

CREATE TABLE clubes (
    id_club NUMBER(2) CONSTRAINT pk_clubes PRIMARY KEY,
    nombre VARCHAR2(60) NOT NULL,
    descripcion VARCHAR2(200) NOT NULL,
    cod_postal NUMBER(5) NOT NULL,
    direccion VARCHAR2(200) NOT NULL,
    id_pais NUMBER(2) NOT NULL,
    id_ciudad NUMBER(2) NOT NULL,
    cuota_membr VARCHAR2(1) CONSTRAINT ck_cuotaclub CHECK (cuota_membr in('S','N')),
    id_institucion NUMBER(2),
    CONSTRAINT fk_localizacionclub FOREIGN KEY(id_pais,id_ciudad) REFERENCES ciudades(id_pais,id_ciudad),
    CONSTRAINT fk_institucionclub FOREIGN KEY (id_institucion) REFERENCES instituciones (id_institucion),
    CONSTRAINT check_cuota_institucion CHECK(id_institucion is NULL or cuota_membr = 'N')
);

CREATE TABLE HIST_MEMBRESIAS(
    ID_CLUB NUMBER(2) NOT NULL,
    ID_LECTOR NUMBER(3) NOT NULL,
    F_ING_CLUB DATE DEFAULT SYSDATE NOT NULL,
    F_SOL_RETIRO DATE,
    F_RETIRO DATE,
    MOTIVO_RETIRO VARCHAR2(2) CONSTRAINT CHECK_MEMBRESIA_MOTIVO_RETIRO CHECK(MOTIVO_RETIRO IN ('DE', 'VO', 'IN', 'OT')),
    CONSTRAINT FK_MEMBRESIA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT FK_MEMBRESIA_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT PK_HIST_MEMBRESIA PRIMARY KEY(ID_CLUB, ID_LECTOR, F_ING_CLUB)
);

CREATE TABLE OBRAS_ACTUADAS(
    ID_CLUB NUMBER(2) NOT NULL,
    ID_OBRA NUMBER(2) NOT NULL,
    TITULO VARCHAR2(50) NOT NULL,
    DURACION_MINUTOS NUMBER(3) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    ACTIVA VARCHAR2(1) NOT NULL CONSTRAINT CHECK_OBRA_ACTIVA CHECK(ACTIVA = 'S' OR ACTIVA = 'N'),
    COSTO NUMBER(6, 2),
    CONSTRAINT FK_OBRA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_OBRA PRIMARY KEY(ID_CLUB, ID_OBRA)
);

CREATE TABLE ASOCIACIONES(
    ID_CLUB NUMBER(2) NOT NULL,
    ID_SOCIO NUMBER(2) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_ASOCIACION_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT FK_ASOCIACION_SOCIO FOREIGN KEY(ID_SOCIO) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_ASOCIACION PRIMARY KEY(ID_CLUB, ID_SOCIO)
);

CREATE TABLE TELEFONOS(
    CODIGO_PAIS NUMBER(3) NOT NULL,
    CODIGO_AREA NUMBER(5) NOT NULL,
    NUMERO NUMBER(9) NOT NULL,
    ID_LECTOR NUMBER(3),
    ID_CLUB NUMBER(2),
    CONSTRAINT PK_TELEFONO PRIMARY KEY (CODIGO_PAIS, CODIGO_AREA, NUMERO),
    CONSTRAINT FK_TELEFONO_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT FK_TELEFONO_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT CHECK_ARCO_TELEFONO CHECK(
        (ID_LECTOR IS NULL AND ID_CLUB IS NOT NULL) OR
        (ID_LECTOR IS NOT NULL AND ID_CLUB IS NULL)
    )
);

CREATE TABLE HABLA(
    ID_IDIOMA NUMBER(2) NOT NULL,
    ID_HABLA NUMBER(2) NOT NULL,
    ID_LECTOR NUMBER(3),
    ID_CLUB NUMBER(2),
    CONSTRAINT FK_HABLA_IDIOMA FOREIGN KEY(ID_IDIOMA) REFERENCES IDIOMAS(ID_IDIOMA),
    CONSTRAINT FK_HABLA_LECTOR FOREIGN KEY(ID_LECTOR) REFERENCES LECTORES(ID_LECTOR),
    CONSTRAINT FK_HABLA_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_HABLA PRIMARY KEY(ID_IDIOMA, ID_HABLA),
    CONSTRAINT CHECK_ARCO_HABLA CHECK(
        (ID_LECTOR IS NULL AND ID_CLUB IS NOT NULL) OR
        (ID_LECTOR IS NOT NULL AND ID_CLUB IS NULL)
    )
);

CREATE TABLE GRUPOS_LECTURA(
    ID_CLUB NUMBER(2) NOT NULL,
    ID_GRUPO NUMBER(2) NOT NULL,
    TIPO VARCHAR2(1) NOT NULL CONSTRAINT CHECK_GRUPO_TIPO CHECK(TIPO IN('N', 'J', 'A')),
    DIA NUMBER(1) NOT NULL CONSTRAINT CHECK_GRUPO_DIA CHECK(DIA >= 2 AND DIA <= 6),
    HORA DATE NOT NULL CONSTRAINT CHECK_GRUPO_HORA CHECK(TO_CHAR(HORA, 'HH24:MI') BETWEEN '17:00' AND '19:00'),
    F_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_GRUPO_CLUB FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB),
    CONSTRAINT PK_GRUPO PRIMARY KEY(ID_CLUB, ID_GRUPO),
    CONSTRAINT CHECK_HORA_NINOS CHECK (TIPO <> 'N' OR TO_CHAR(HORA, 'HH24:MI') = '17:00')
);

CREATE TABLE PAGOS_MEMBRESIA (
    id_club NUMBER(2) NOT NULL,
    id_lector NUMBER(3) NOT NULL,
    f_ing_club DATE NOT NULL,
    id_pago NUMBER(2) NOT NULL,
    f_pago DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_PAGOS_MEMB_HIST FOREIGN KEY (id_club, id_lector, f_ing_club) 
        REFERENCES HIST_MEMBRESIAS(id_club, id_lector, f_ing_club),
    CONSTRAINT PK_PAGOS_MEMBRESIA PRIMARY KEY (id_club, id_lector, f_ing_club, id_pago)
);

CREATE TABLE HIST_ASIGNACIONES (
    id_club_grupo NUMBER(2) NOT NULL,
    id_grupo NUMBER(2) NOT NULL,
    id_club_memb NUMBER(2) NOT NULL,
    id_lector NUMBER(3) NOT NULL,
    f_ing_club DATE NOT NULL,
    f_ing_grupo DATE DEFAULT SYSDATE NOT NULL,
    f_fin_grupo DATE,
    CONSTRAINT FK_ASIGNACION_GRUPO FOREIGN KEY(ID_CLUB_GRUPO, ID_GRUPO) 
        REFERENCES GRUPOS_LECTURA(ID_CLUB, ID_GRUPO),
    CONSTRAINT FK_ASIGNACION_MEMBRESIA FOREIGN KEY(ID_CLUB_MEMB, ID_LECTOR, F_ING_CLUB) 
        REFERENCES HIST_MEMBRESIAS(ID_CLUB, ID_LECTOR, F_ING_CLUB),
    CONSTRAINT PK_ASIGNACION  PRIMARY KEY(ID_CLUB_GRUPO, ID_GRUPO, ID_CLUB_MEMB, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
);

CREATE TABLE ADAPTACIONES (
    id_club NUMBER(2) NOT NULL,
    id_obra NUMBER(2) NOT NULL,
    isbn NUMBER(13) NOT NULL,
    CONSTRAINT FK_ADAP_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT FK_ADAP_LIBRO FOREIGN KEY (isbn) REFERENCES LIBROS(isbn),
    CONSTRAINT PK_ADAPTACIONES PRIMARY KEY (id_club, id_obra, isbn)
);

CREATE TABLE ELENCOS (
    id_club NUMBER(2) NOT NULL,
    id_obra NUMBER(2) NOT NULL,
    id_lector NUMBER(3) NOT NULL,
    CONSTRAINT FK_ELEN_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT FK_ELEN_LECTOR FOREIGN KEY (id_lector) REFERENCES LECTORES(id_lector),
    CONSTRAINT PK_ELENCOS PRIMARY KEY (id_club, id_obra, id_lector)
);

CREATE TABLE PRESENTACIONES (
    id_club NUMBER(2) NOT NULL,
    id_obra NUMBER(2) NOT NULL,
    f_presentacion DATE NOT NULL,
    valoracion NUMBER(3,2) NOT NULL CONSTRAINT CHECK_PRESENTACION_VALORACION CHECK((VALORACION >= 0) AND (VALORACION <= 5)),
    n_entradas NUMBER(2) NOT NULL,
    CONSTRAINT FK_PRES_OBRA FOREIGN KEY (id_club, id_obra) REFERENCES OBRAS_ACTUADAS(id_club, id_obra),
    CONSTRAINT PK_PRESENTACIONES PRIMARY KEY (id_club, id_obra, f_presentacion)
);

CREATE TABLE MEJORES_ACTORES (
    id_club_el NUMBER(2) NOT NULL,
    id_obra_el NUMBER(2) NOT NULL,
    id_lector NUMBER(3) NOT NULL,
    id_club_pres NUMBER(2) NOT NULL,
    id_obra_pres NUMBER(2) NOT NULL,
    f_presentacion DATE NOT NULL,
    CONSTRAINT FK_MEJOR_ACTOR_ELENCO FOREIGN KEY(ID_CLUB_EL, ID_OBRA_EL, ID_LECTOR)
        REFERENCES ELENCOS(ID_CLUB, ID_OBRA, ID_LECTOR),
    CONSTRAINT FK_MEJOR_ACTOR_PRESENTACION FOREIGN KEY(ID_CLUB_PRES, ID_OBRA_PRES, F_PRESENTACION)
        REFERENCES PRESENTACIONES(ID_CLUB, ID_OBRA, F_PRESENTACION),
    CONSTRAINT PK_MEJOR_ACTOR PRIMARY KEY(ID_CLUB_EL, ID_OBRA_EL, ID_LECTOR, ID_CLUB_PRES, ID_OBRA_PRES, F_PRESENTACION)
);

CREATE TABLE CAL_REUNIONES (
    id_club NUMBER(2) NOT NULL,
    id_grupo NUMBER(2) NOT NULL,
    isbn NUMBER(13) NOT NULL,
    f_reunion DATE NOT NULL,
    realizada VARCHAR2(1) NOT NULL CONSTRAINT CHECK_REUNION_REALIZADA CHECK(realizada = 'S' OR realizada = 'N'),
    id_club_memb_mod NUMBER(2) NOT NULL,
    id_club_grupo_mod NUMBER(2) NOT NULL,
    id_grupo_mod NUMBER(2) NOT NULL,
    id_moderador NUMBER(3) NOT NULL,
    f_ing_club_mod DATE NOT NULL,
    f_ing_grupo_mod DATE NOT NULL,
    conclusiones VARCHAR2(400),
    valoracion NUMBER(1) CONSTRAINT CHECK_REUNION_VALORACION CHECK(valoracion >= 1 AND valoracion <= 5),
    ultima_reunion VARCHAR2(1) CONSTRAINT CHECK_ULTIMA__REUNION CHECK(ultima_reunion = 'S' OR ultima_reunion = 'N'),
    CONSTRAINT FK_GRUPO_CALENDARIO FOREIGN KEY(ID_CLUB, ID_GRUPO) REFERENCES GRUPOS_LECTURA(ID_CLUB, ID_GRUPO),
    CONSTRAINT FK_LIBRO_CALENDARIO FOREIGN KEY(ISBN) REFERENCES LIBROS(ISBN),
    CONSTRAINT FK_MODERADOR FOREIGN KEY(ID_CLUB_MEMB_MOD, ID_CLUB_GRUPO_MOD, ID_GRUPO_MOD, ID_MODERADOR, F_ING_CLUB_MOD, F_ING_GRUPO_MOD)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB_MEMB, ID_CLUB_GRUPO, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT PK_CALENDARIO PRIMARY KEY(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT CHECK_REUNION_OPCIONALES CHECK(realizada = 'N' or NVL(ultima_reunion, 'N') = 'N' or (conclusiones IS NOT NULL AND valoracion is NOT NULL))
);

CREATE TABLE INASISTENCIAS(
    ID_CLUB_GRUPO NUMBER(2) NOT NULL,
    ID_CLUB_MEMB NUMBER(2) NOT NULL,
    ID_GRUPO_ASIG NUMBER(2) NOT NULL,
    ID_LECTOR NUMBER(3) NOT NULL,
    F_ING_CLUB DATE NOT NULL,
    F_ING_GRUPO DATE NOT NULL,
    ID_CLUB_CAL NUMBER(2) NOT NULL,
    ID_GRUPO_CAL NUMBER(2) NOT NULL,
    ISBN NUMBER(13) NOT NULL,
    F_REUNION DATE NOT NULL,
    CONSTRAINT FK_INASISTENCIA_ASIGNACION FOREIGN KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT FK_INASISTENCIA_CALENDARIO FOREIGN KEY(ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
        REFERENCES CAL_REUNIONES(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT PK_INASISTENCIA PRIMARY KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO, ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
);