CREATE TABLE INASISTENCIAS(
    ID_CLUB_GRUPO NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_CLUB_GRUPO,
    ID_CLUB_MEMB NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_CLUB_MEMBBRESIA,
    ID_GRUPO_ASIG NUMBER(2) CONSTRAINT NN_INASISTENCIA_ID_GRUPO_ASIGNACION,
    ID_LECTOR NUMBER(3) CONSTRAINT NN_INASISTENCIA_ID_LECTOR,
    F_ING_CLUB DATE CONSTRAINT NN_INASISTENCIA_F_ING_CLUB,
    F_ING_GRUPO CONSTRAINT NN_INASISTENCIA_F_ING_GRUPO,
    ID_CLUB_CAL CONSTRAINT NN_INASISTENCIA_ID_CLUB_CALENDARIO,
    ID_GRUPO_CAL CONSTRAINT NN_INASISTENCIA_ID_GRUPO_CALENDARIO,
    ISBN CONSTRAINT NN_INASISTENCIA_ISBN_LIBRO,
    F_REUNION CONSTRAINT NN_INASISTENCIA_F_REUNION,
    CONSTRAINT FK_INASISTENCIA_ASIGNACION FOREIGN KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO)
        REFERENCES HIST_ASIGNACIONES(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO),
    CONSTRAINT FK_INASISTENCIA_CALENDARIO FOREIGN KEY(ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
        REFERENCES CAL_REUNIONES(ID_CLUB, ID_GRUPO, ISBN, F_REUNION),
    CONSTRAINT PRIMARY KEY(ID_CLUB_GRUPO, ID_CLUB_MEMB, ID_GRUPO_ASIG, ID_LECTOR, F_ING_CLUB, F_ING_GRUPO, ID_CLUB_CAL, ID_GRUPO_CAL, ISBN, F_REUNION)
);
