CREATE SEQUENCE S_AUTOR INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_REPRESENTANTE INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_INSTITUCION INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_IDIOMA INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_PAIS INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_LECTOR INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE S_CLUB INCREMENT BY 1 START WITH 1;